Add cpu build and test to windows CI

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -212,6 +212,9 @@ pytorch_ios_params: &pytorch_ios_params
 
 pytorch_windows_params: &pytorch_windows_params
   parameters:
+    executor:
+      type: string
+      default: "windows-cpu-with-nvidia-cuda"
     test_name:
       type: string
       default: ""
@@ -497,6 +500,9 @@ jobs:
   pytorch_windows_build:
     <<: *pytorch_windows_params
     parameters:
+      executor:
+        type: string
+        default: "windows-cpu-with-nvidia-cuda"
       test_name:
         type: string
         default: ""
@@ -518,7 +524,7 @@ jobs:
       use_cuda:
         type: string
         default: ""
-    executor: windows-cpu-with-nvidia-cuda
+    executor: <<parameters.executor>>
     steps:
       - checkout
       - run:
@@ -531,37 +537,41 @@ jobs:
           name: Install Cuda
           no_output_timeout: 30m
           command: |
-            curl --retry 3 -kLO https://ossci-windows.s3.amazonaws.com/cuda_10.1.243_426.00_win10.exe
-            7z x cuda_10.1.243_426.00_win10.exe -ocuda_10.1.243_426.00_win10
-            cd cuda_10.1.243_426.00_win10
-            mkdir cuda_install_logs
-            ./setup.exe -s nvcc_10.1 cuobjdump_10.1 nvprune_10.1 cupti_10.1 cublas_10.1 cublas_dev_10.1 cudart_10.1 cufft_10.1 cufft_dev_10.1 curand_10.1 curand_dev_10.1 cusolver_10.1 cusolver_dev_10.1 cusparse_10.1 cusparse_dev_10.1 nvgraph_10.1 nvgraph_dev_10.1 npp_10.1 npp_dev_10.1 nvrtc_10.1 nvrtc_dev_10.1 nvml_dev_10.1 -loglevel:6 -log:"$(pwd -W)/cuda_install_logs"
-            if [[ "${VC_YEAR}" == "2017" ]]; then
-              cp -r CUDAVisualStudioIntegration/extras/visual_studio_integration/MSBuildExtensions/* "C:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/Common7/IDE/VC/VCTargets/BuildCustomizations/"
-            else
-              cp -r CUDAVisualStudioIntegration/extras/visual_studio_integration/MSBuildExtensions/* "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/MSBuild/Microsoft/VC/v160/BuildCustomizations/"
+            if [[ "${USE_CUDA}" == "1" ]]; then
+              curl --retry 3 -kLO https://ossci-windows.s3.amazonaws.com/cuda_10.1.243_426.00_win10.exe
+              7z x cuda_10.1.243_426.00_win10.exe -ocuda_10.1.243_426.00_win10
+              cd cuda_10.1.243_426.00_win10
+              mkdir cuda_install_logs
+              ./setup.exe -s nvcc_10.1 cuobjdump_10.1 nvprune_10.1 cupti_10.1 cublas_10.1 cublas_dev_10.1 cudart_10.1 cufft_10.1 cufft_dev_10.1 curand_10.1 curand_dev_10.1 cusolver_10.1 cusolver_dev_10.1 cusparse_10.1 cusparse_dev_10.1 nvgraph_10.1 nvgraph_dev_10.1 npp_10.1 npp_dev_10.1 nvrtc_10.1 nvrtc_dev_10.1 nvml_dev_10.1 -loglevel:6 -log:"$(pwd -W)/cuda_install_logs"
+              if [[ "${VC_YEAR}" == "2017" ]]; then
+                cp -r CUDAVisualStudioIntegration/extras/visual_studio_integration/MSBuildExtensions/* "C:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/Common7/IDE/VC/VCTargets/BuildCustomizations/"
+              else
+                cp -r CUDAVisualStudioIntegration/extras/visual_studio_integration/MSBuildExtensions/* "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/MSBuild/Microsoft/VC/v160/BuildCustomizations/"
+              fi
+              curl --retry 3 -kLO https://ossci-windows.s3.amazonaws.com/NvToolsExt.7z
+              7z x NvToolsExt.7z -oNvToolsExt
+              mkdir -p "C:/Program Files/NVIDIA Corporation/NvToolsExt"
+              cp -r NvToolsExt/* "C:/Program Files/NVIDIA Corporation/NvToolsExt/"
+              export NVTOOLSEXT_PATH="C:\\Program Files\\NVIDIA Corporation\\NvToolsExt\\"
+              cat cuda_install_logs/LOG.setup.exe.log
+              if ! ls "/c/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/bin/nvcc.exe"
+              then
+                echo "CUDA installation failed"
+                exit 1
+              fi
+              cd ..
+              rm -rf ./cuda_10.1.243_426.00_win10
+              rm -f ./cuda_10.1.243_426.00_win10.exe
             fi
-            curl --retry 3 -kLO https://ossci-windows.s3.amazonaws.com/NvToolsExt.7z
-            7z x NvToolsExt.7z -oNvToolsExt
-            mkdir -p "C:/Program Files/NVIDIA Corporation/NvToolsExt"
-            cp -r NvToolsExt/* "C:/Program Files/NVIDIA Corporation/NvToolsExt/"
-            export NVTOOLSEXT_PATH="C:\\Program Files\\NVIDIA Corporation\\NvToolsExt\\"
-            cat cuda_install_logs/LOG.setup.exe.log
-            if ! ls "/c/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/bin/nvcc.exe"
-            then
-              echo "CUDA installation failed"
-              exit 1
-            fi
-            cd ..
-            rm -rf ./cuda_10.1.243_426.00_win10
-            rm -f ./cuda_10.1.243_426.00_win10.exe
       - run:
           name: Install Cudnn
           command : |
-            cd c:/
-            curl --retry 3 -O https://ossci-windows.s3.amazonaws.com/cudnn-10.1-windows10-x64-v7.6.4.38.zip
-            7z x cudnn-10.1-windows10-x64-v7.6.4.38.zip -ocudnn
-            cp -r cudnn/cuda/* "C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/"
+            if [[ "${USE_CUDA}" == "1" ]]; then
+              cd c:/
+              curl --retry 3 -O https://ossci-windows.s3.amazonaws.com/cudnn-10.1-windows10-x64-v7.6.4.38.zip
+              7z x cudnn-10.1-windows10-x64-v7.6.4.38.zip -ocudnn
+              cp -r cudnn/cuda/* "C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/"
+            fi
       - run:
           name: Build
           no_output_timeout: "90m"
@@ -575,6 +585,9 @@ jobs:
   pytorch_windows_test:
     <<: *pytorch_windows_params
     parameters:
+      executor:
+        type: string
+        default: "windows-cpu-with-nvidia-cuda"
       test_name:
         type: string
         default: ""
@@ -596,7 +609,7 @@ jobs:
       use_cuda:
         type: string
         default: ""
-    executor: windows-with-nvidia-gpu
+    executor: <<parameters.executor>>
     steps:
       - checkout
       - run:
@@ -1943,6 +1956,7 @@ workflows:
                 - /release\/.*/
       - pytorch_windows_test:
           name: pytorch_windows_vs2017_14.11_py36_cuda10.1_test1
+          executor: windows-with-nvidia-gpu
           test_name: pytorch-windows-test1
           cuda_version: "10"
           python_version: "3.6"
@@ -1961,6 +1975,7 @@ workflows:
                 - /release\/.*/
       - pytorch_windows_test:
           name: pytorch_windows_vs2017_14.11_py36_cuda10.1_test2
+          executor: windows-with-nvidia-gpu
           test_name: pytorch-windows-test2
           cuda_version: "10"
           python_version: "3.6"
@@ -1995,6 +2010,7 @@ workflows:
                 - /release\/.*/
       - pytorch_windows_test:
           name: pytorch_windows_vs2017_14.16_py36_cuda10.1_test1
+          executor: windows-with-nvidia-gpu
           test_name: pytorch-windows-test1
           cuda_version: "10"
           python_version: "3.6"
@@ -2013,6 +2029,7 @@ workflows:
                 - /release\/.*/
       - pytorch_windows_test:
           name: pytorch_windows_vs2017_14.16_py36_cuda10.1_test2
+          executor: windows-with-nvidia-gpu
           test_name: pytorch-windows-test2
           cuda_version: "10"
           python_version: "3.6"
@@ -2041,6 +2058,7 @@ workflows:
             - setup
       - pytorch_windows_test:
           name: pytorch_windows_vs2019_py36_cuda10.1_test1
+          executor: windows-with-nvidia-gpu
           test_name: pytorch-windows-test1
           cuda_version: "10"
           python_version: "3.6"
@@ -2053,6 +2071,7 @@ workflows:
             - pytorch_windows_vs2019_py36_cuda10.1_build
       - pytorch_windows_test:
           name: pytorch_windows_vs2019_py36_cuda10.1_test2
+          executor: windows-with-nvidia-gpu
           test_name: pytorch-windows-test2
           cuda_version: "10"
           python_version: "3.6"
@@ -2063,6 +2082,144 @@ workflows:
           requires:
             - setup
             - pytorch_windows_vs2019_py36_cuda10.1_build
+      - pytorch_windows_build:
+          name: pytorch_windows_vs2017_14.11_py36_cpu_build
+          cuda_version: "cpu"
+          python_version: "3.6"
+          vc_version: "14.11"
+          vc_year: "2017"
+          vc_product: "BuildTools"
+          use_cuda: "0"
+          requires:
+            - setup
+          filters:
+            branches:
+              only:
+                - master
+                - /ci-all\/.*/
+                - /release\/.*/
+      - pytorch_windows_test:
+          name: pytorch_windows_vs2017_14.11_py36_cpu_test1
+          test_name: pytorch-windows-test1
+          cuda_version: "cpu"
+          python_version: "3.6"
+          vc_version: "14.11"
+          vc_year: "2017"
+          vc_product: "BuildTools"
+          use_cuda: "0"
+          requires:
+            - setup
+            - pytorch_windows_vs2017_14.11_py36_cpu_build
+          filters:
+            branches:
+              only:
+                - master
+                - /ci-all\/.*/
+                - /release\/.*/
+      - pytorch_windows_test:
+          name: pytorch_windows_vs2017_14.11_py36_cpu_test2
+          test_name: pytorch-windows-test2
+          cuda_version: "cpu"
+          python_version: "3.6"
+          vc_version: "14.11"
+          vc_year: "2017"
+          vc_product: "BuildTools"
+          use_cuda: "0"
+          requires:
+            - setup
+            - pytorch_windows_vs2017_14.11_py36_cpu_build
+          filters:
+            branches:
+              only:
+                - master
+                - /ci-all\/.*/
+                - /release\/.*/
+      - pytorch_windows_build:
+          name: pytorch_windows_vs2017_14.16_py36_cpu_build
+          cuda_version: "cpu"
+          python_version: "3.6"
+          vc_version: "14.16"
+          vc_year: "2017"
+          vc_product: "BuildTools"
+          use_cuda: "0"
+          requires:
+            - setup
+          filters:
+            branches:
+              only:
+                - master
+                - /ci-all\/.*/
+                - /release\/.*/
+      - pytorch_windows_test:
+          name: pytorch_windows_vs2017_14.16_py36_cpu_test1
+          test_name: pytorch-windows-test1
+          cuda_version: "cpu"
+          python_version: "3.6"
+          vc_version: "14.16"
+          vc_year: "2017"
+          vc_product: "BuildTools"
+          use_cuda: "0"
+          requires:
+            - setup
+            - pytorch_windows_vs2017_14.16_py36_cpu_build
+          filters:
+            branches:
+              only:
+                - master
+                - /ci-all\/.*/
+                - /release\/.*/
+      - pytorch_windows_test:
+          name: pytorch_windows_vs2017_14.16_py36_cpu_test2
+          test_name: pytorch-windows-test2
+          cuda_version: "cpu"
+          python_version: "3.6"
+          vc_version: "14.16"
+          vc_year: "2017"
+          vc_product: "BuildTools"
+          use_cuda: "0"
+          requires:
+            - setup
+            - pytorch_windows_vs2017_14.16_py36_cpu_build
+          filters:
+            branches:
+              only:
+                - master
+                - /ci-all\/.*/
+                - /release\/.*/
+      - pytorch_windows_build:
+          name: pytorch_windows_vs2019_py36_cpu_build
+          cuda_version: "cpu"
+          python_version: "3.6"
+          vc_version: ""
+          vc_year: "2019"
+          vc_product: "Community"
+          use_cuda: "0"
+          requires:
+            - setup
+      - pytorch_windows_test:
+          name: pytorch_windows_vs2019_py36_cpu_test1
+          test_name: pytorch-windows-test1
+          cuda_version: "cpu"
+          python_version: "3.6"
+          vc_version: ""
+          vc_year: "2019"
+          vc_product: "Community"
+          use_cuda: "0"
+          requires:
+            - setup
+            - pytorch_windows_vs2019_py36_cpu_build
+      - pytorch_windows_test:
+          name: pytorch_windows_vs2019_py36_cpu_test2
+          test_name: pytorch-windows-test2
+          cuda_version: "cpu"
+          python_version: "3.6"
+          vc_version: ""
+          vc_year: "2019"
+          vc_product: "Community"
+          use_cuda: "0"
+          requires:
+            - setup
+            - pytorch_windows_vs2019_py36_cpu_build
       - pytorch_linux_build:
           name: pytorch_linux_xenial_pynightly_build
           requires:
